type: kubernetes
kind: pipeline
name: default

steps:
- name: prepare database
  image: mysql:8
  commands:
    - apt update && apt install -y wait-for-it
    - wait-for-it lvh.me:3306
    - mysql -u root --password=traefik -h lvh.me CSI20CRSF < CSI20CRSF.sql

- name: test
  image: gradle:6.7.0-jdk11
  environment:
    SONAR_TOKEN:
      from_secret: SONAR_TOKEN
  commands:
    - ./gradlew clean test
    - ./gradlew sonarqube -Dsonar.projectKey=csi -Dsonar.host.url=https://sonarqube.intl.krosf.com -Dsonar.login=$SONAR_TOKEN

services:
- name: lvh.me
  image: mysql:8
  environment:
    MYSQL_PASSWORD: traefik
    MYSQL_ROOT_PASSWORD: traefik
    MYSQL_USER: traefik
    MYSQL_DATABASE: CSI20CRSF